add windows support
srisham/wizlightcpp pull request #9
Opened 2023-09-06 15:23 UTC by xTarzx

udp.cpp
  - use winsock api
CMakeLists.txt
  - add windows specific includes
 
removed "using namespace std" from all files to avoid "byte" name clash

build script for windows included

2023-09-07 03:31 UTC, srisham commented on include/bulb.h
> +    void setDeviceIP(const std::string &ip);
Most developers would prefer writing `std::string& ` than `std::string &`

2023-09-07 03:33 UTC, srisham commented on src/bulb.cpp
> +    json_t *root = json_object();
Same here. Can you please undo these changes? I would prefer `<type>* ` than `<type> *`

2023-09-07 03:36 UTC, srisham requested changes
1. Most developers would prefer writing `<type>* `  than `<type> *`. Please revert it.
2. And squash your 2 commits into 1 and update the PR.

2023-09-07 14:05 UTC, xTarzx reviewed
Changes done.

2023-09-07 14:06 UTC, xTarzx reviewed
not sure how this works

2023-09-08 02:28 UTC, srisham approved these changes

2023-09-08 02:29 UTC, merged